#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRONTEND_DIR="$PROJECT_DIR/src/frontend"
ENV_FILE="$PROJECT_DIR/.env"
FRONTEND_ENV_FILE="$FRONTEND_DIR/.env.local"

prompt_value() {
    local label="$1"
    local default_value="$2"
    local value

    read -r -p "$label [$default_value]: " value
    if [[ -z "$value" ]]; then
        value="$default_value"
    fi
    printf '%s' "$value"
}

prompt_port() {
    local label="$1"
    local default_value="$2"
    local value

    while true; do
        value="$(prompt_value "$label" "$default_value")"
        if [[ "$value" =~ ^[0-9]+$ ]] && (( value >= 1 && value <= 65535 )); then
            printf '%s' "$value"
            return
        fi
        echo "端口必须是 1-65535 之间的数字。"
    done
}

quote_value() {
    local value="$1"
    printf "'%s'" "${value//\'/\'\\\'\'}"
}

write_env_line() {
    local key="$1"
    local value="$2"
    printf '%s=%s\n' "$key" "$(quote_value "$value")"
}

echo "Dice Room 交互式配置"
echo

site="$(prompt_value "Caddy 站点地址；真实域名可填 example.com" "http://localhost:8088")"
backend_address="$(prompt_value "后端监听地址" "127.0.0.1")"
backend_port="$(prompt_port "后端监听端口" "8080")"
backend_target_default="$backend_address:$backend_port"
caddy_backend="$(prompt_value "Caddy 反向代理目标" "$backend_target_default")"
webroot="$(prompt_value "前端构建产物目录" "$FRONTEND_DIR/dist")"
frontend_host="$(prompt_value "前端开发服务器监听地址" "0.0.0.0")"
frontend_port="$(prompt_port "前端开发服务器端口" "5173")"
api_target="$(prompt_value "前端开发期 API 代理目标" "http://localhost:$backend_port")"

cat > "$ENV_FILE" <<EOF
# Generated by ./configure.sh
$(write_env_line DICE_ROOM_SITE "$site")
$(write_env_line DICE_ROOM_SERVER_ADDRESS "$backend_address")
$(write_env_line DICE_ROOM_SERVER_PORT "$backend_port")
$(write_env_line DICE_ROOM_BACKEND "$caddy_backend")
$(write_env_line DICE_ROOM_WEBROOT "$webroot")
$(write_env_line DICE_ROOM_FRONTEND_HOST "$frontend_host")
$(write_env_line DICE_ROOM_FRONTEND_PORT "$frontend_port")
$(write_env_line VITE_API_TARGET "$api_target")
EOF

cat > "$FRONTEND_ENV_FILE" <<EOF
# Generated by ../../configure.sh
$(write_env_line DICE_ROOM_SERVER_PORT "$backend_port")
$(write_env_line DICE_ROOM_FRONTEND_HOST "$frontend_host")
$(write_env_line DICE_ROOM_FRONTEND_PORT "$frontend_port")
$(write_env_line VITE_API_TARGET "$api_target")
EOF

echo
echo "已写入："
echo "- $ENV_FILE"
echo "- $FRONTEND_ENV_FILE"
echo
echo "常用命令："
echo "- 生产运行：./run.sh"
echo "- 后端开发：source .env && mvn -Dserver.address=\"\$DICE_ROOM_SERVER_ADDRESS\" -Dserver.port=\"\$DICE_ROOM_SERVER_PORT\" compile exec:java"
echo "- 前端开发：cd src/frontend && npm run dev"
